// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcodzjvagxxsqivivxpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjb2R6anZhZ3h4c3Fpdml2eHBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjE4MDEsImV4cCI6MjA2NjIzNzgwMX0.9DujNDCWF_MGU21qBFghTUhYBqNcvDjOsD6S_TUH-Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);